## 扫描原始数据

In [29]:
from pathlib import Path

root = Path("/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/")

subdirs = [p for p in root.iterdir() if p.is_dir()]

for d in subdirs:
    print(f"\"{d.name}\",")
for d in subdirs:
    print(f"\"{d.resolve()}\",")

"Desktop_sw2_0615_0605_none",
"Desktop_sw2_0706_0615_none",
"Desktop_sw2_0730_0706",
"Desktop_sw2_0826_0730",
"Desktop_sw2_0927_0826_none",
"/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0615_0605_none",
"/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0706_0615_none",
"/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0730_0706",
"/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0826_0730",
"/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0927_0826_none",

## 完整性检查_生成表格_按时间检查

### 导入数据

In [ ]:
%%time

from pathlib import Path
import pandas as pd
from datetime import datetime
from PIL import Image


export_csv_name = "ms2_0605_0923"

root_list = [
    # ms1
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/ms1/Desktop_ms1_0706_0605",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/ms1/Desktop_ms1_0730_0707",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/ms1/Desktop_ms1_0826_0730",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/ms1/Desktop_ms1_0927_0826",
    # ms2
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/ms2/Desktop_ms2_0706_0605",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/ms2/Desktop_ms2_0730_0705",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/ms2/Desktop_ms2_0826_0730",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/ms2/Desktop_ms2_0927_0826",
    # air1
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/air1/Desktop_air1_0711_0701_none",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/air1/Desktop_air1_0806_0712",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/air1/Desktop_air1_0909_0826",
    # air2
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/air2/Desktop_air2_0805_0701",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/air2/Desktop_air2_0823_0805",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/air2/Desktop_air2_0909_0824",
    # jeff
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/jeff/Desktop_jeff_0521_0519_none",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/jeff/Desktop_jeff_0606_0601_none",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/jeff/Desktop_jeff_0707_0611",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/jeff/Desktop_jeff_0828_0707",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/jeff/Desktop_jeff_1011_0829_none",
    # lloyd
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/lloyd/Desktop_lloyd_0521_0513_none",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/lloyd/Desktop_lloyd_0606_0531",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/lloyd/Desktop_lloyd_0617_0611",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/lloyd/Desktop_lloyd_0711_0617",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/lloyd/Desktop_lloyd_0805_0711",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/lloyd/Desktop_lloyd_0830_0805",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/lloyd/Desktop_lloyd_0909_0829",
    # southfarm1
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/southfarm1/Desktop_southfarm1_0712_0701",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/southfarm1/Desktop_southfarm1_0903_0823_none",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/southfarm1/Desktop_southfarm1_1011_0911",
    # southfarm2
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/southfarm2/Desktop_southfarm2_0805_0712_none",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/southfarm2/Desktop_southfarm2_0823_0805_none",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/southfarm2/Desktop_southfarm2_1011_0824_none",
    # sw1
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw1/Desktop_sw1_0606_0605",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw1/Desktop_sw1_0615_0605",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw1/Desktop_sw1_0706_0615",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw1/Desktop_sw1_0730_0705",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw1/Desktop_sw1_0826_0731",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw1/Desktop_sw1_0927_0826",
    # sw2
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0615_0605_none",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0706_0615_none",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0730_0706",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0826_0730",
    # "/media/tianqi/16tb/SWD/01_Data/2024_SWD_data_RAW/eachFarm/sw2/Desktop_sw2_0927_0826_none",

    # other
    "/home/tianqi/D/01_Projects/01_swd/02_code/pipeline/ultralytics_ty/_ty/01_data/a04_whole_raw_data/ms2_0605_0923/" 
]

sub_path = "images/4656x3496_autofocus/"
sub_path = ""

year = 2024                     # 改年份（如果不是2024）

rows = []

for root in map(Path, root_list):
    for p in root.rglob(sub_path + "*.jpg"):
        try:
            # 0729_0606_620.jpg
            mmdd, hhmm, focal = p.stem.split("_")

            dt = datetime(
                year,
                int(mmdd[:2]),
                int(mmdd[2:]),
                int(hhmm[:2]),
                int(hhmm[2:])
            )

            # rows.append({
            #     "path": str(p),
            #     "datetime": dt,
            #     "focal": int(focal),
            # })

            with Image.open(p) as im:
                w, h = im.size

            rows.append({
                "path": str(p),
                "datetime": dt,
                "focal": int(focal),
                "resolution": f"{w}x{h}",
            })


        except:
            pass   # 如果文件名不符合格式就跳过

df = pd.DataFrame(rows)
df = df.sort_values("datetime")

df

CPU times: user 382 ms, sys: 46.7 ms, total: 429 ms
Wall time: 438 ms

,path,datetime,focal,resolution
11164,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 11:33:00,700,4656x3496
8957,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 12:01:00,700,4656x3496
6917,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 12:31:00,700,4656x3496
599,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 13:01:00,700,4656x3496
1729,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 13:31:00,700,4656x3496
...,...,...,...,...
2656,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:21:00,540,4656x3496
8428,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:23:00,580,4656x3496
2255,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:24:00,600,4656x3496
8580,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:25:00,640,4656x3496
4910,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:27:00,680,4656x3496

### 展开_分解_数据__导出点1

In [31]:
df1 = df.copy()
# Split datetime column into date and time
df1[['date', 'time']] = df1['datetime'].astype(str).str.split(' ', expand=True)

# Calculate time differences between rows in minutes
time_diffs_minutes = df1['datetime'].diff().dt.total_seconds() / 60
df1['gap_time']= time_diffs_minutes
# export csv file
df1.to_csv(f"{export_csv_name}.csv", index=False)
df1

,path,datetime,focal,resolution,date,time,gap_time
11164,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 11:33:00,700,4656x3496,2024-06-05,11:33:00,NaN
8957,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 12:01:00,700,4656x3496,2024-06-05,12:01:00,28.0
6917,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 12:31:00,700,4656x3496,2024-06-05,12:31:00,30.0
599,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 13:01:00,700,4656x3496,2024-06-05,13:01:00,30.0
1729,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-06-05 13:31:00,700,4656x3496,2024-06-05,13:31:00,30.0
...,...,...,...,...,...,...,...
2656,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:21:00,540,4656x3496,2024-09-23,19:21:00,24.0
8428,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:23:00,580,4656x3496,2024-09-23,19:23:00,2.0
2255,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:24:00,600,4656x3496,2024-09-23,19:24:00,1.0
8580,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:25:00,640,4656x3496,2024-09-23,19:25:00,1.0
4910,/home/tianqi/D/01_Projects/01_swd/02_code/pipe...,2024-09-23 19:27:00,680,4656x3496,2024-09-23,19:27:00,2.0

### GroupBy__data,focal__每日的开始和结束时间

In [32]:
df2 = df1.copy()
# Extract daily start and end times, calculate duration in hours:minutes, and count images
daily_summary = (
    df2.groupby(["date", "focal"])
    .agg(
        start_time=("time", "first"),
        end_time=("time", "last"),
        image_count=("path", "count"),
    )
    .reset_index()
)
# Calculate duration in hours:minutes format
start_dt = pd.to_datetime(daily_summary["start_time"], format="%H:%M:%S")
end_dt = pd.to_datetime(daily_summary["end_time"], format="%H:%M:%S")

duration = end_dt - start_dt

# 处理跨午夜（例如 23:50 -> 00:10）
duration = duration.where(duration >= pd.Timedelta(0), duration + pd.Timedelta(days=1))

sec = duration / pd.Timedelta(seconds=1)

hh = (sec // 3600).astype(int)
mm = ((sec % 3600) // 60).astype(int)

daily_summary["duration(hh:mm)"] = (
    hh.astype(str).str.zfill(2) + ":" + mm.astype(str).str.zfill(2)
)

# Assign result back to df
df2 = daily_summary
# Ensure the result is a DataFrame
if not isinstance(df2, pd.DataFrame):
    df2 = pd.DataFrame({"Answer": [df2]})
df2

           date  focal start_time  end_time  image_count duration(hh:mm)
0    2024-06-05    700   11:33:00  20:31:00           19           08:58
1    2024-06-06    700   06:02:00  20:31:00           30           14:29
2    2024-06-07    700   06:02:00  20:31:00           30           14:29
3    2024-06-08    700   06:02:00  20:31:00           30           14:29
4    2024-06-09    700   06:02:00  20:31:00           29           14:29
..          ...    ...        ...       ...          ...             ...
425  2024-09-23    540   06:01:00  19:21:00           12           13:20
426  2024-09-23    580   06:03:00  19:23:00           12           13:20
427  2024-09-23    600   14:24:00  19:24:00           11           05:00
428  2024-09-23    640   14:25:00  19:25:00           11           05:00
429  2024-09-23    680   14:27:00  19:27:00           11           05:00

[430 rows x 6 columns]

### 提取focal列表

In [33]:
df_focal_list = df2.copy()
# Extract unique values from 'focal' column
unique_focal_list = df_focal_list['focal'].unique().tolist()
unique_focal_list

[700, 580, 600, 620, 640, 660, 680, 540]

### 确保'date'列连续，填补缺失日期__导出点2_最后一张表

In [34]:
out = []
for focal in unique_focal_list:
    print(f"focal: {focal}")
    df3 = df2.copy()
    # Filter dataframe for rows where 'focal' equals xxx
    df3 = df3[df3['focal'] == focal]
    # Ensure 'date' column is continuous, filling missing dates
    df3['date'] = pd.to_datetime(df3['date'], errors='coerce').dt.date
    df3 = df3.sort_values(by='date')
    all_dates = pd.date_range(start=df3['date'].min(), end=df3['date'].max(), freq='D').date
    df3 = df3.set_index('date').reindex(all_dates).rename_axis('date').reset_index()
    df3["focal"] = focal
    display(df3)
    out.append(df3)
df_merged = pd.concat(out, ignore_index=True)
print(f"Final merged dataframe shape: {df_merged.shape}")
# export csv file
df_merged.to_csv(f"{export_csv_name}_proc.csv", index=False)
df_merged

focal: 700

          date  focal start_time  end_time  image_count duration(hh:mm)
0   2024-06-05    700   11:33:00  20:31:00           19           08:58
1   2024-06-06    700   06:02:00  20:31:00           30           14:29
2   2024-06-07    700   06:02:00  20:31:00           30           14:29
3   2024-06-08    700   06:02:00  20:31:00           30           14:29
4   2024-06-09    700   06:02:00  20:31:00           29           14:29
5   2024-06-10    700   06:02:00  20:32:00           30           14:30
6   2024-06-11    700   06:02:00  20:31:00           30           14:29
7   2024-06-12    700   06:02:00  20:31:00           30           14:29
8   2024-06-13    700   06:01:00  20:31:00           30           14:30
9   2024-06-14    700   06:01:00  20:31:00           30           14:30
10  2024-06-15    700   06:00:00  21:05:00           31           15:05
11  2024-06-16    700   06:00:00  20:30:00           30           14:30
12  2024-06-17    700   06:02:00  20:31:00           30           14:29
13  2024-06-18    700   06:02:00  20:31:00           30           14:29
14  2024-06-19    700   06:02:00  20:31:00           30           14:29
15  2024-06-20    700   06:02:00  20:32:00           30           14:30
16  2024-06-21    700   06:02:00  20:31:00           30           14:29
17  2024-06-22    700   06:02:00  20:31:00           30           14:29
18  2024-06-23    700   06:02:00  20:31:00           30           14:29
19  2024-06-24    700   06:02:00  20:31:00           30           14:29
20  2024-06-25    700   06:02:00  20:31:00           30           14:29
21  2024-06-26    700   06:02:00  20:31:00           30           14:29
22  2024-06-27    700   06:02:00  20:31:00           30           14:29
23  2024-06-28    700   06:02:00  20:31:00           30           14:29
24  2024-06-29    700   06:02:00  20:31:00           30           14:29
25  2024-06-30    700   06:02:00  20:31:00           30           14:29
26  2024-07-01    700   06:02:00  20:31:00           30           14:29
27  2024-07-02    700   06:02:00  20:31:00           30           14:29
28  2024-07-03    700   06:02:00  20:31:00           30           14:29
29  2024-07-04    700   06:02:00  20:31:00           30           14:29
30  2024-07-05    700   06:02:00  20:31:00           29           14:29

focal: 580

          date  focal start_time  end_time  image_count duration(hh:mm)
0   2024-07-06    580   06:08:00  20:36:00           30           14:28
1   2024-07-07    580   06:08:00  20:37:00           30           14:29
2   2024-07-08    580   06:04:00  20:33:00           30           14:29
3   2024-07-09    580   06:04:00  20:33:00           30           14:29
4   2024-07-10    580   06:04:00  20:33:00           30           14:29
..         ...    ...        ...       ...          ...             ...
75  2024-09-19    580   06:04:00  20:33:00           30           14:29
76  2024-09-20    580   06:04:00  20:34:00           30           14:30
77  2024-09-21    580   06:04:00  20:34:00           30           14:30
78  2024-09-22    580   06:04:00  20:50:00           25           14:46
79  2024-09-23    580   06:03:00  19:23:00           12           13:20

[80 rows x 6 columns]

focal: 600

          date  focal start_time  end_time  image_count duration(hh:mm)
0   2024-07-06    600   06:09:00  20:38:00         30.0           14:29
1   2024-07-07    600   06:09:00  20:39:00         30.0           14:30
2   2024-07-08    600   06:05:00  20:34:00         30.0           14:29
3   2024-07-09    600   06:05:00  20:34:00         30.0           14:29
4   2024-07-10    600   06:05:00  20:34:00         30.0           14:29
..         ...    ...        ...       ...          ...             ...
75  2024-09-19    600   06:05:00  20:34:00         30.0           14:29
76  2024-09-20    600   06:05:00  20:35:00         30.0           14:30
77  2024-09-21    600   06:05:00  20:35:00         30.0           14:30
78  2024-09-22    600   06:05:00  20:51:00         25.0           14:46
79  2024-09-23    600   14:24:00  19:24:00         11.0           05:00

[80 rows x 6 columns]

focal: 620

         date  focal start_time  end_time  image_count duration(hh:mm)
0  2024-07-06    620   06:10:00  20:39:00           30           14:29
1  2024-07-07    620   06:10:00  20:40:00           29           14:30

focal: 640

          date  focal start_time  end_time  image_count duration(hh:mm)
0   2024-07-06    640   06:12:00  20:40:00         30.0           14:28
1   2024-07-07    640   06:12:00  20:41:00         29.0           14:29
2   2024-07-08    640   06:07:00  20:35:00         30.0           14:28
3   2024-07-09    640   06:07:00  20:35:00         30.0           14:28
4   2024-07-10    640   06:07:00  20:35:00         30.0           14:28
..         ...    ...        ...       ...          ...             ...
75  2024-09-19    640   06:06:00  20:35:00         30.0           14:29
76  2024-09-20    640   06:06:00  20:36:00         30.0           14:30
77  2024-09-21    640   06:06:00  20:36:00         30.0           14:30
78  2024-09-22    640   06:06:00  20:52:00         25.0           14:46
79  2024-09-23    640   14:25:00  19:25:00         11.0           05:00

[80 rows x 6 columns]

focal: 660

         date  focal start_time  end_time  image_count duration(hh:mm)
0  2024-07-06    660   06:13:00  20:42:00           30           14:29
1  2024-07-07    660   06:13:00  20:43:00           29           14:30

focal: 680

          date  focal start_time  end_time  image_count duration(hh:mm)
0   2024-07-06    680   06:15:00  20:43:00         30.0           14:28
1   2024-07-07    680   06:15:00  20:44:00         29.0           14:29
2   2024-07-08    680   06:08:00  20:37:00         30.0           14:29
3   2024-07-09    680   06:08:00  20:37:00         30.0           14:29
4   2024-07-10    680   06:08:00  20:37:00         30.0           14:29
..         ...    ...        ...       ...          ...             ...
75  2024-09-19    680   06:08:00  20:37:00         30.0           14:29
76  2024-09-20    680   06:08:00  20:38:00         30.0           14:30
77  2024-09-21    680   06:08:00  20:38:00         30.0           14:30
78  2024-09-22    680   06:08:00  20:54:00         24.0           14:46
79  2024-09-23    680   14:27:00  19:27:00         11.0           05:00

[80 rows x 6 columns]

focal: 540

          date  focal start_time  end_time  image_count duration(hh:mm)
0   2024-07-08    540   06:03:00  20:31:00           30           14:28
1   2024-07-09    540   06:03:00  20:31:00           30           14:28
2   2024-07-10    540   06:03:00  20:31:00           30           14:28
3   2024-07-11    540   06:03:00  20:31:00           30           14:28
4   2024-07-12    540   06:03:00  20:32:00           30           14:29
..         ...    ...        ...       ...          ...             ...
73  2024-09-19    540   06:02:00  20:31:00           30           14:29
74  2024-09-20    540   06:02:00  20:32:00           30           14:30
75  2024-09-21    540   06:02:00  20:32:00           30           14:30
76  2024-09-22    540   06:02:00  20:48:00           25           14:46
77  2024-09-23    540   06:01:00  19:21:00           12           13:20

[78 rows x 6 columns]

Final merged dataframe shape: (433, 6)

           date  focal start_time  end_time  image_count duration(hh:mm)
0    2024-06-05    700   11:33:00  20:31:00         19.0           08:58
1    2024-06-06    700   06:02:00  20:31:00         30.0           14:29
2    2024-06-07    700   06:02:00  20:31:00         30.0           14:29
3    2024-06-08    700   06:02:00  20:31:00         30.0           14:29
4    2024-06-09    700   06:02:00  20:31:00         29.0           14:29
..          ...    ...        ...       ...          ...             ...
428  2024-09-19    540   06:02:00  20:31:00         30.0           14:29
429  2024-09-20    540   06:02:00  20:32:00         30.0           14:30
430  2024-09-21    540   06:02:00  20:32:00         30.0           14:30
431  2024-09-22    540   06:02:00  20:48:00         25.0           14:46
432  2024-09-23    540   06:01:00  19:21:00         12.0           13:20

[433 rows x 6 columns]